
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://orderapi_user:password@db:5432/api8inf349
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    command: rq worker -u redis://redis:6379 payment_queue
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

volumes:
  pgdata:
